### ISSUE TITLE
Use an established license

### ISSUE THREAD

**Issue by akien-mga** [genete/Minehunter#1]
Hi there,

Congrats on this project, it looks good and runs well :)

I see in the README.md that you intend to have a very permissive license for your game:

> This project is fully free for you with no restrictions.

However it's often considered a good practice to use an existing license text to define such permissions, so that people can quickly see "OK this is MIT/CC0/GPL/<anything else>, I know what that implies".

See e.g. http://choosealicense.org. If you want to make it public domain (i.e. waive your copyright) you can use the Unlicense license: http://choosealicense.com/licenses/unlicense
Otherwise you can keep your copyright and use the MIT license which is among the most permissive: http://choosealicense.com/licenses/mit/

**Comment by genete** [comment]
Thanks for the point. Relicensed is done now under MIT.

**Comment by akien-mga** [comment]
Awesome, thanks :)
